version: '3'

services:
  local-vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test123
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    ports:
      - '8200:8200'
